### ISSUE TITLE
E-mail login requires an adapter

### ISSUE THREAD

**Issue by laoer536** [sidebase/nuxt-auth#109]
### Ask your question

when I use, It report  'E-mail login requires an adapter'. How to resolve?

**Comment by BracketJohn** [comment]
See https://next-auth.js.org/providers/email for a full guide on how to use the email-provider. The error itself seems to indicate that you need to add a adapter: https://next-auth.js.org/adapters/overview

Can you please supply a bigger example / reproduction so that we can debug it? Else it's a bit hard to say where the problem comes from.

**Comment by laoer536** [comment]
Ok! Thanks. 😄
