### ISSUE TITLE
Getting session in an API route

### ISSUE THREAD

**Issue by ngajhede** [sidebase/nuxt-auth#131]
### Ask your question

Hiya. 

So I'm using your fantastic auth module together with tRPC and prisma. So far I've added prisma to my context. But I would like to add my current session to my context as well, so I can use it within my api routes to validate the currently signed in user. My current context.ts-file looks like this:

```ts
import { PrismaClient } from "@prisma/client";
import { inferAsyncReturnType } from "@trpc/server";

export const createContext = () => {
  prisma = new PrismaClient();

  return {
    prisma,
  };
};
export type Context = inferAsyncReturnType<typeof createContext>;

```

In NextJS I would probably add the following and export together with the prisma client, but I've had no luck with getServerSession - it requires a H3Event which I'm not sure what is.
```ts
 const session = await unstable_getServerSession(req, res, nextAuthOptions);
```

How would I go about getting the server session?

**Comment by Q16solver** [comment]
`createContext` actually receives the H3Event from the first argument, but I do agree that getServerSession's api from nuxt auth should be fixed and have the same structure from next auth, I shouldn't need to pass in the whole event argument so it can grab the session, it should only need req and res like next auth, because for websockets, there is no H3Event, but I should still be able to have authenticated websockets and be able to grab the session

**Comment by ngajhede** [comment]
> `createContext` actually receives the H3Event from the first argument unless you're using websockets as well, but I do agree that getServerSession's api from nuxt auth should be fixed up and have the same structure as next auth, I shouldn't need to pass in the whole event argument so it can grab the session, it should only need `req` and `res` like next auth, because for websockets, there is no H3Event, but I should still be able to have authenticated websockets and be able to grab the session.
> 
> This is especially painful when I'm trying to implement auth as middlewares in trpc since I need to propagate the entire event object throughout the context, hopefully this can be fixed c:

Thank you! Saved my day.

And I totally agree. I also had no idea how this worked, especially coming from NextAuth it's confusing. 

Have a wonderful EOY!

**Comment by Q16solver** [comment]
@ngajhede I think we can probably keep this issue open and perhaps put a different tag like `enhancement` to improve the api, what do you think @BracketJohn?

**Comment by Q16solver** [comment]
This might be annoying though from the library side to handle getting the session from the websocket if that's possible, since they have completely different types. The `req` seems to be the same type `IncomingMessage`, just that the `res` is `ws` type compared to `ServerResponse`, and most of the main logic seems to be from the req side, so it should be ok I think

**Comment by BracketJohn** [comment]
Thanks you two for the fruitful discussion.

> Have a wonderful EOY!

same to you!

---

regarding the issue at hand:
- @ngajhede just fyi: you can use `npm create sidebase@latest` to nicely setup `tRPC` -> that setup will also for example add the `event` to the `createContext` call, see [1]
- @Q16solver thanks for the proposal. I'll open a new issue to "widen" support away from `H3Event`s. I have some questions & remarks, so let's discuss in #135!

[1] example of how `create-sidebase` sets up tRPC:
```ts
import { inferAsyncReturnType } from '@trpc/server'
import type { H3Event } from 'h3'

/**
 * Creates context for an incoming request
 * @link https://trpc.io/docs/context
 */
export async function createContext(event: H3Event) {

// ...
```
