### ISSUE TITLE
Access `.env` in `NextAuthHandler`

### ISSUE THREAD

**Issue by vencho-mdp** [sidebase/nuxt-auth#134]
### Ask your question

Hi! I think the title is quite self-explanatory, but I have no idea how we could do this. Happy new year!

**Comment by BracketJohn** [comment]
Happy new year to you to @vencho-mdp!

Thanks for the q -> what you want to do is rather something that should be (and is!) natively supported by Nuxt 3.

Here's the related docs: https://nuxt.com/docs/api/composables/use-runtime-config

TLDR:
- use `useRuntimeConfig()` to get the env-vars
- use a `.env` file for dev / generate
- use the platform environment (i.e.: `export NUXT_ENV_VAR=1`) to set env vars during production

See the `using the .env file` section for further `.env` specific information (: 

You can also checkout the strapi-recipe from our docs that uses the `.env` file + `useRuntimeConfig` setup that I described above.

Overall, this issue is rather nuxt 3 related, so I'd encourage you to ask for further support in the Nuxt 3 repo: https://github.com/nuxt/framework or hop onto discord https://discord.gg/9MUHR8WT9B.

Let me know if there's anything else, otherwise I'm closing this as answered now (:

**Comment by vencho-mdp** [comment]
Hi @BracketJohn . I knew that but where should we place the composable? Outside the handler?
