### ISSUE TITLE
wrong icons/logos url

### ISSUE THREAD

**Issue by Jericho1060** [sidebase/nuxt-auth#151]
### Describe the bug

on the login page, the logo of each provider is not displayed.
![image](https://user-images.githubusercontent.com/28439359/211372456-cf0f33fa-c2fe-4e83-808c-0831d3d48939.png)

### Additional context

it just seems the URL for each image is not valid anymore

**Comment by BracketJohn** [comment]
Hey @Jericho1060 👋 

Thanks for the report - yes, this is a very unfortunate problem that comes due to a repo-reorganization by next-auth! This is why the icons cannot be loaded anylonger.

It will be fixed by our upcoming switch to `auth.js`:  #117

I've added your issue to that issue and will close this one so that we have all tracking in one place. Checkout that issue for updated on this issue 🐑

**Comment by Jericho1060** [comment]
No problem, was just reporting it.
Anyway, i'm using a custom page, with my own icons actually.

Just seen it while testing something for a new project.

Thank you for your answer.

**Comment by BracketJohn** [comment]
yeah - and it's awesome that you did ❤️

**Comment by BracketJohn** [comment]
Hey @Jericho1060 👋 

Small update: We're actually going to be able to fix this pre-auth.js bump as @balazsorban44 provided a release for the "old" next-auth that fixes this.

So we're jumping to `4.18.8` now and that will fix the icons issue. Next we do the jump to `auth.js` (:

**Comment by Jericho1060** [comment]
Hey @BracketJohn
Thank you for the feedback.

**Comment by BracketJohn** [comment]
Sure! Try out `0.4.0-alpha.3`, icons are working again 🎊
