### ISSUE TITLE
Api path are absolute and not relative

### ISSUE THREAD

**Issue by Jericho1060** [sidebase/nuxt-auth#207]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.4.1`
- Builder:          `vite`
- User Config:      `app`, `auth`, `css`, `modules`, `nitro`, `runtimeConfig`, `i18n`, `build`
- Runtime Modules:  `nuxt-monaco-editor@1.1.3`, `@nuxtjs/i18n@8.0.0-beta.9`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`
------------------------------

### Reproduction

`npx nuxi dev`

### Describe the bug

I never tried that before.
I just wanted to test something with my backend and seen that in dev environment, when trying to access the app from my network address (from another pc), all the default functions like getProviders() are using absolute path to query the api.

So when on http://192.168.0.179:8080 if I'm calling getProviders() in vue, it's querying http://localhost:8080/api/auth/providers

So it's just resulting in 404 errors.

![image](https://user-images.githubusercontent.com/28439359/216762531-eb8c1158-bf60-49d2-9fa8-059e583405d2.png)

### Additional context

The full code in my Vue page

```js
<template>
  <div class="container">
    <div class="row my-auto">
      <div class="col my-auto text-center" style="overflow-y: auto;">
        <div v-for="provider in providers">
          <button class="btn-primary btn w-100 mb-1 text-white" @click="signIn(provider.id)">
            Login With {{ provider.name }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const {signIn, data, getProviders} = useSession();
const session = data.value;

const providers = await getProviders();
</script>
```

**Comment by BracketJohn** [comment]
Hey @Jericho1060 👋 

The `origin` is inferred automatically during development if it is not explicitly set. Nuxt exposes dev-applications on two network interfaces per default:
1. localhost -> the `local:` one
2. "public" local network -> the `network:` one

nuxt-auth can only be used with one specific origin, so we need to choose one of these. To be as conservative as possible the `local:` part is chosen, to not accidentally expose something to the local network that the user does not want.

If you want to override this, you can do so by:
- setting `origin: 'http://182.168.0.179` in your `nuxt.config.ts` _at build time_ (so, basically before running `npm run dev`)
- setting `export AUTH_ORIGIN=http://182.168.0.179` in your terminal before running `npm run dev` / `npm run preview` / `npm run start`

That said this is expected behavior, as explained above. Closing this issue now, let me know if you need any further assistance / I would also be happy to hear from you if this helped you (:
