### ISSUE TITLE
How to use Advanced initialization ?

### ISSUE THREAD

**Issue by Mateleo** [sidebase/nuxt-auth#227]
### Ask your question

I was wandering how to use Advanced initialization like this :
https://next-auth.js.org/configuration/initialization

My problem right now is that i cannot access session during signIn callback. It may be possible if I could have NuxtAuthHandler in a classic defineEventHandler(event).

**Comment by zoey-kaiser** [comment]
Hello @Mateleo 👋 

Have you tried to use the code snippet from NextAuth and just insert it into the NextAuthHandler?
I am unsure if it will work but its worth a try.

**Comment by satya-500** [comment]
> ### Ask your question
> I was wandering how to use Advanced initialization like this : https://next-auth.js.org/configuration/initialization
> 
> My problem right now is that i cannot access session during signIn callback. It may be possible if I could have NuxtAuthHandler in a classic defineEventHandler(event).
> 
> ### Additional information
> _No response_

```js
callbacks: {
        signIn: async({ user, account, profile, email, credentials }) => {
            var backlist = {
                'email_id': [
                    'heisenberg@xxxxx.cc',
                    'heisenberg@xxxxx.cc'
                ]
            }
            if (backlist['email_id'].includes(user?.email!)) {
                console.log('you are blacklisted')
                return false
            } else {
                return true
            }
        }
    }
```

**Comment by jtswm** [comment]
Hello,

I'm also wondering how to use advanced initialization. I need to run async code before initializing. I have tried something like this:

`import { NuxtAuthHandler } from '#auth'

export default defineEventHandler(async (event) => {
  // Do whatever you want here, before the request is passed down to `NuxtAuthHandler`
  await ...

  return NuxtAuthHandler({
    providers: [
      ...
    ],
  })(event)
})
`

This seems to work, but I am getting a warning:
`You setup the auth handler for a second time - this is likely undesired. Make sure that you only call NuxtAuthHandler( ... ) once`

It seems calling the NuxtAuthHandler on each request is not supported. 

Is there another way to set up advanced initialization?

**Comment by Mateleo** [comment]
Yes I got the same error!

**Comment by jtswm** [comment]
Hi @zoey-kaiser,

Can this be reopened to help us understand if advanced initialization is supported by nuxt-auth, and if it is, how to use it correctly? (My previous post shows the code I tried.)

Thank you!

**Comment by janhoogeveen** [comment]
The above snippet seems to work well, but the error message is discouraging indeed.
Fwiw, I'm using it to conditionally show providers depending on an API call.

**Comment by BracketJohn** [comment]
Hey!

To understand this better: What kind of initialization are you trying to perform? Maybe it's better suited to be in a nitro server plugin, separate from the auth handler?You could do it there, store the config and then use the config in the auth handler.

About the warning: This is mostly a performance related issue, so if the perf. is still good enough for you, you can proceed with the workaround described by @jtswm here: https://github.com/sidebase/nuxt-auth/issues/227#issuecomment-1458887474

**Comment by BracketJohn** [comment]
> My use-case is the same as in the next-auth docs, modifying the providers array. I do an API call to retrieve auth configuration per client and pass that to nuxt-auth.

do you need to modify them on every call? if not, you could also do it as a one-time fetch on server-startup to avoid this warning.

Another way to avoid the warning or at least reduce it: Cache your setup nuxt-auth-handlers - do a one time setup per different providers set. if its the same providers load the cached version (e.g., by storing them in an object where serialized, ordered provideres are the key).

Anyways: As this (for now) looks like a niche-edge-case I'd love to resolve this by having some docs about it, instead of adding a code-feature. Would you be willing to write a recipe / guide with:
- your use case
- the different work-arounds we discussed here (counting 3 so far)
  - ignoring message
  - caching different handlers to reduce amount of messages
  - doing it as a top-level one time setup at server-start time

That would be super beneficial for you and others in the future!

**Comment by janhoogeveen** [comment]
> do you need to modify them on every call? if not, you could also do it as a one-time fetch on server-startup to avoid this warning.

I only have one deployment serving multiple clients, based on the subdomain. Since every request could be coming from a different subdomain, the configuration needs to be looked up on every request. 

A one-time fetch would be nice, if I knew up-front the clients I need to serve. Maybe I can use that to pre-populate a cache of known clients, and unknown clients can be added to that cache dynamically.

> Another way to avoid the warning or at least reduce it: Cache your setup nuxt-auth-handlers - do a one time setup per different providers set. if its the same providers load the cached version (e.g., by storing them in an object where serialized, ordered provideres are the key).

Not a bad idea! I've been running this advanced initialization deployed on a development server for a couple of days now, and the auth handlers become noticeably slower. I'll have to look into some form of caching soon. If I find a good solution I can share that, of course.

> Anyways: As this (for now) looks like a niche-edge-case I'd love to resolve this by having some docs about it, instead of adding a code-feature. Would you be willing to write a recipe / guide with:

If I find a scaleable solution I'm happy with, absolutely 👍🏻 .
