### ISSUE TITLE
signIn does not set cookies when called on the server

### ISSUE THREAD

**Issue by Desuuuu** [sidebase/nuxt-auth#238]
### Environment

nuxt-auth: 0.4.1
provider: OAuth

```
- Operating System: `Windows_NT`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.25.1`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `build`, `components`, `typescript`, `vueuse`, `inkline`, `auth`, `runtimeConfig`
- Runtime Modules:  `@vueuse/nuxt@9.11.1`, `@inkline/nuxt@3.1.4`, `@sidebase/nuxt-auth@0.4.1`
- Build Modules:    `-`
```

### Reproduction

* Configure the Google OAuth provider
* Set it as the `defaultProvider`
* Visit a protected page (you are redirected to Google directly)
* Login with Google

You should have been redirected to the signin page with an OAuth error and there should be a `checks.state argument is missing` message in the server console.

### Describe the bug

The `signIn` function sends a POST request to the `/api/auth/signin/PROVIDER` url.

With the default OAuth configuration, this request sets cookies which are required to validate the OAuth result (for the state/pkce checks).

These cookies are not propagated to the client when the call is made on the server, resulting in a `checks.state argument is missing` error from `next-auth`.

### Additional context

https://github.com/sidebase/nuxt-auth/blob/c231ae839dc180c03a67bdf8ca44df1aa58da8b1/src/runtime/composables/useSession.ts#L150-L161

**Comment by hcmlopes** [comment]
I am experiencing the same issue is there a workaround currently that will allow oAuth providers like google or Auth0 to work?

**Comment by BracketJohn** [comment]
Hey @hcmlopes 👋 

Sorry for the inconvenience - a fix is started in #253, but @Desuuuu didn't have tim eyet to finish it.

**Comment by hcmlopes** [comment]
@BracketJohn Since upgrading all packages to latest version I am not having this issue anymore, except when deploying to netlify which I can't even be sure it is the same error.

I worked with @zoey-kaiser to try and fix the netlify issue but we weren't able to get to too much insight into the errors

**Comment by zoey-kaiser** [comment]
> I worked with @zoey-kaiser to try and fix the netlify issue but we weren't able to get to too much insight into the errors

Yes, we did! However I am still trying to find some time to look into properly testing the ideas we formed during the call!

**Comment by BracketJohn** [comment]
As this issue is inactive and pertains to quite the old version of `nuxt-auth` let's close it and re-open a more specific one with a reproduction when it comes up again!

It'd also be super nice if any results of your investigation result in a new issue / a PR with docs / ... (:

Thanks and have a good sunday (:
