### ISSUE TITLE
refresh-token-rotation - jwt callback doesn't always update the stored token

### ISSUE THREAD

**Issue by dscheibel** [sidebase/nuxt-auth#287]
### Ask your question

I'm trying to connect to an external backend based on simple jwt authentication (the external backend is based on this boilerplate: https://github.com/hagopj13/node-express-boilerplate)

I'm trying to implement the refresh-token-rotation (https://authjs.dev/guides/basics/refresh-token-rotation) solution based on this gist: https://gist.github.com/vanling/b10ebe14ee90ff249bea28bf94abb745 

I'm running into issues when doing a browser-refresh and the api-token needs to go through the rotation. 

I think the problem i'm running into is that the jwt callback doesn't always store the return token on the server. Initial Sign in works. When i refresh the session from the hydrated page, it works as expected, but when i try a browser refresh, the updated token from the external api is passed back to the page via the session at first, but not stored on the server. With the next refresh, the old jwt-token gets returned and rotation breaks.

Here is the implementation of the callbacks:
```
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'
let count = 0;

async function refreshAccessToken(tokens: {
  accessToken: string;
  accessTokenExpires: string;
  refreshToken: string;
  refreshTokenExpires: string,
}) {
    // [ ... ] it does it's thing successfully and returns the result:
    return { accessToken, accessTokenExpires, refreshToken, refreshTokenExpires };
}

export default NuxtAuthHandler({
  secret: process.env.AUTH_SECRET || 'the-most-amazing-project-ever',
  session: {
    strategy: "jwt",
    maxAge: 5 * 60, 
  },
  providers: [
    CredentialsProvider.default({
      name: "Credentials",
      credentials: {
        email: { label: "Email", type: "text" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials: any) {
        // [ ... ] logs in user successfully ..
        return user;
      },
    }),
  ],
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      console.warn("Sign in callback:", { user, account, profile, email, credentials });
      return true
    },
    async jwt({ token, user, account, profile, isNewUser }) {
      console.warn("JWT callback", { token, user, account, profile, isNewUser });
      if (!token.tests) token.tests = [];
      token.tests.push(`jwt(${count++})`);  
      if (account && user) {
        return {
          ...token,
          ...user,
        };
      }
      if (token.accessTokenExpires && Date.now() > Date.parse(token.accessTokenExpires)) {
        const newTokens = await refreshAccessToken(token);
        const newToken = {
          ...token,
          ...newTokens,
        }
        return newToken;
      }
      return token;
    },
    async session({ session, token }) {
      session.user = {
        ...session.user,
        tests: token.tests,
        accessToken: token.accessToken,
        accessTokenExpires: token.accessTokenExpires,
      };
      return session;
    },
  },
})

```
To test my theory i added a `test` array to the token. 
Upon sign in, the session returns 
```
Status: authenticated
Data: {
  "user": {
    "name": "Daniel",
    "email": "daniel@xx.com",
    "tests": [
      "jwt(0)",
      "jwt(1)"
    ],
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjQyMmI0OGE5OWI4YjdlY2RjMTljNzciLCJpYXQiOjE2Nzg4NzM2MjEsImV4cCI6MTY3ODg3MzY1MSwidHlwZSI6ImFjY2VzcyJ9.Eua8a5MtDub-o_zFOkYJYZHzSbP50Ll_YwqUyTU7YvU",
    "accessTokenExpires": "2023-03-15T09:47:31.941Z"
  },
  "expires": "2023-03-15T09:52:01.964Z"
}
```
But when i query the token from the server, the response is 
```
Decoded JWT token: {
  "name": "Daniel",
  "email": "daniel@xx.com",
  "sub": "624xxxx8a99b8b7ecdcxxxxx",
  "tests": [
    "jwt(0)"
  ],
  "id": "624xxxx8a99b8b7ecdcxxxxx",
  "accessToken": "xx",
  "accessTokenExpires": "2023-03-15T09:54:25.770Z",
  "refreshToken": "xx",
  "refreshTokenExpires": "2023-03-16T09:53:55.770Z",
  "iat": 1678874035,
  "exp": 1681466035,
  "jti": "84dfba35-8d5d-4d59-be84-375bc3562cec"
}
```
This already shows that the token on the server is out of sync with what the session returns. (The jwt callback has been called one more time which is not stored on the server-token.)

Refreshing the token via `getSession` from the hydrated site continues like expected:
```
"tests": [
      "jwt(0)",
      "jwt(2)",
      "jwt(3)",
      "jwt(4)",
    ],
```
But with a browser-refresh it only adds a new array item on the session but it's not stored on the server token.. so after multiple refreshes the session returns something like this
```
"tests": [
    "jwt(0)",
    "jwt(2)",
    "jwt(3)",
    "jwt(4)",
    "jwt(11)"
  ],
```
  while the server-token is stuck at 
```
"tests": [
    "jwt(0)",
    "jwt(2)",
    "jwt(3)",
    "jwt(4)",
  ],
```
  
  I would expect that the token stays in sync either way and always stores the token returned from the jwt-callback.
  
  I submitted this as a question, as i'm not sure if this is nuxt-auth, next-auth or project related.
  Anyone else running into this issue?

**Comment by BracketJohn** [comment]
Hey @dscheibel 👋 

Thanks for the question - could you provide a repro for this? I sadly cannot help based on just the information you gave (although that was plenty! (: )

**Comment by KoenCa** [comment]
I think I'm having the same issue. First I thought it was a race condition which caused the refresh token rotation to fail, but now I'm starting to believe it is something else. 

I have pretty much the same credentials setup that includes a function for rotating the access and refresh tokens. I also have the refetch interval for the session set to 5 seconds and when fetching data from secured API endpoints I pass along the access token which I get from the session. I also have a wrapper around the `useSession` (now `useAuth`) hook that also checks if there was an error while refreshing and if there was then the `signOut` function is called.

When I login and just stay active in the current tab or leave the tab open and go to other tabs everything seems to be working fine. I don't get logged out.

The problem arises when I close the tab and come back later while the access token has been expired or refresh the page while the access token has been expired. In this situation as a user I expect to be still logged in, but the user gets logged out. So when I noticed this I started debugging/researching this. You probably have seen my comments about race conditions in other issues which I thought was the issue. 

Today in my research I have discovered that there is no proper sync between server and client when it comes to the session. So I will describe what happens when a user gets logged out:
1. User refreshes or visits website again, but his access token is expired.
2. Website starts loading via SSR so server side
3. Refresh token logic is triggered which calls the back-end API endpoint to refresh the tokens.
    - This returns new access and refresh tokens. **The old refresh token is blacklisted in the back-end for security reasons!**
4. Website is being loaded
    - Non secured pages load fine
    - Secured pages with API calls that need the access token also load fine. These API calls also occur server side, because we use `useFetch`, so I guess they use the properly updated session. 
5. Now when the user is on the website the refetch interval for the session starts running. After 5 seconds I wants to update the session and then it goes wrong. The refresh token logic is executed again which is not logical, because the user session was just updated server side while loading via SSR, right? Well in a way it is logical, because the client still sends along the **old non refreshed session**! So there was no session sync at all from server to client?
6. Result: user gets logged out, but they still should be logged in, because we have a long lifetime for the refresh tokens. 

I discovered this by logging several steps of the refresh rotation logic. For debugging purposes I also set the access token expiration to be 20 seconds. Below I show a screenshot with this logging with some explanations:

![CleanShot 2023-04-13 at 18 11 09](https://user-images.githubusercontent.com/17332418/231824323-4971157a-1069-4767-a83f-1cc72f6c44f4.png)

Not sure if this problem is is nuxt-auth, next-auth or Nuxt 3. I tried rewriting our front-end auth using the example provided by Nuxt 3 maintainers: https://github.com/nuxt/examples/tree/main/auth/local . But I also abandoned that, because there I also got what I thought were race conditions, but maybe it was also caused by no sync between client and server?

I hope this is clear and can help, because I really would like to see this resolved, but it is not easy.

Related race condition issue: https://github.com/sidebase/nuxt-auth/issues/239

**Comment by KoenCa** [comment]
After updating to Nuxt 3.4.1 (from 3.3.3) it should be solved. At least in my scenario. The session gets refreshed on the server and then not again when the client is loaded like it should work.

**Comment by BracketJohn** [comment]
Yay, glad to hear!

And thanks so much for the long-form analysis!

Let's see if @dscheibel still has anything to add.

**Comment by dscheibel** [comment]
Just got around to test this again.. 
After updating to the latest versions (nuxt@3.4.2, @sidebase/nuxt-auth@0.4.4), this is working as expected.
Tokens stay in sync on server and client side. 
Thank you.

**Comment by BracketJohn** [comment]
Perfect! (:
