### ISSUE TITLE
useAuth() or useSession()

### ISSUE THREAD

**Issue by krxdow** [sidebase/nuxt-auth#313]
### Ask your question

I have a Nuxt project , and I installed  **nuxt-auth** with `npm i -D @sidebase/nuxt-auth`
I can see in your example, you manage and access sessions with **useAuth()** in my case it's not defined in my project.
So I use useSession   , what are differences? how work with useAuth()  in Nuxt project

**Comment by BracketJohn** [comment]
What version are you using? The current v0.5.0 RC contains a renaming from useSession to useAuth, so that's likely the difference!

Maybe we can highlight this in the docs?

**Comment by krxdow** [comment]
Thank you for your response, I did not see the release section

**Comment by lookto** [comment]
Is there a reason for changing the docs already? While @sidebase/create still installs @sidebase/nuxt-auth:0.4.3 (not even 0.4.4) the official docs are already changed for v0.5.0 RC. 

I'm not sure if the docs should get changes of release candidates that are not yet in production. The current docs are wrong regarding using useAuth() if sidebase is installed using the same docs "Quickstart" section.

**Comment by BracketJohn** [comment]
Hey @lookto 👋 

Thanks for the thoughtful reply + PR!

I agree that it's not ideal to have the docs reflect the RC state. The idea to already have it was because the RC is considered quite stable + and what people can already start to use (as it's expected to be released line this without changes anyways)

The create sidebase cli distribution is independent of this, but I agree that a dependency actually exists when the cli creates it with an oldish version. Solution to this would be versioned docs.

Alas, for the future we'll do better (eg by not updating docs before final release, then only "testers" may be confused, but it's okay as they're testers).

For now we can:
- merge your PR for a version bump
- have a new PR here to add a big info box on the initial docs page saying: v0.5 changed useSession to useAuth

would you be willing to open the latter? I'm travelling at the moment and it's hard for me to do commits

**Comment by lookto** [comment]
@BracketJohn Sorry, life was busy yesterday and today. Opened the pull request (#318).

**Comment by BracketJohn** [comment]
No worries - I just reviewed & approved, will go live if tests run through (:

**Comment by lookto** [comment]
Happy to contribute. I'm still at the beginning of my sidebase journey but really like it already. If there is an opportunity in the future I won't hesitate to help again.

**Comment by krxdow** [comment]
Hi @lookto  
Thank you for your answers .
It can be closed

**Comment by cmpadden** [comment]
Would we be able to bump the version of `nuxt-auth` in [nuxt-auth-example](https://github.com/sidebase/nuxt-auth-example) to >0.5.0, and update references of `useSession` to `useAuth`? I haven't bumped the version, but updated the references in the following PR, but I suspect there are other changes required (in addition to the version bump) for the example to work.

https://github.com/sidebase/nuxt-auth-example/pull/29
