### ISSUE TITLE
Cannot pass cookies from credentials signin

### ISSUE THREAD

**Issue by mkierdev** [sidebase/nuxt-auth#358]
### Describe the bug

Looking through docs and trying myself, I cannot find a way to pass cookies in signin method.

Flow:
- Users signs in on frontend with signIn() method
- credentials provider sends request to our backend in authorize function
- backend responds with json data, as well as set-cookie header

**There is currently no way to pass that set-cookie back to client.**

I've read about passing cookies with useFetch, however this is not a case as we are using signIn() built-in method. Also, we can't use any Nitro magic, as NuxtAuthHandler does not take H3event as a param.

**Comment by BracketJohn** [comment]
The cookie that authjs sets is http only so that it is explicitly not accessible from frontend JS.

If you want app-side access to the cookie you can follow the docs here: https://sidebase.io/nuxt-auth/server-side/jwt-access#application-side-jwt-token-access

Feel free to respond and tell me if that helped or if we need to re-open this issue. Thanks and have a good sunday 🌞
