### ISSUE TITLE
NEXTAUTH_URL has to be specified when deploying to Netlify

### ISSUE THREAD

**Issue by raducretu** [sidebase/nuxt-auth#370]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.15.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      ssr, target, modules, buildModules, css, runtimeConfig, auth, apollo, colorMode
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @nuxtjs/color-mode@3.2.0, @nuxtjs/apollo@5.0.0-alpha.6, nuxt-lodash@2.4.1, @sidebase/nuxt-auth@0.6.0-beta.0, @vueuse/nuxt@9.13.0, nuxt-icon@0.3.3, @pinia/nuxt@0.4.9
- Build Modules:    -
------------------------------

### Describe the bug

The origin is not set correctly, and NEXTAUTH_URL has precedence over NUXT_ORIGIN, AUTH_ORIGIN, ORIGIN

**Comment by mpringlehlk** [comment]
We also noticed this in our Azure environments, and this warning began appearing recently in STDOUT: 
```
[next-auth][warn][NEXTAUTH_URL]                                                                                                                                                         
https://next-auth.js.org/warnings#nextauth_url
```
Had to add that variable to set origin on deployment.

Node: v18.16.0
Nuxt: v3.2.2
Nuxt-Auth: v0.4.4
Next-Auth: v4.22.1
Builder: Vite

**Comment by tfjordside** [comment]
This is also happening on our azure setup now (started a couple of days ago, without setup change). The NEXTAUTH_URL is now needed for it to work.

**Comment by zoey-kaiser** [comment]
Hi! I have looked into this myself before, but never had enough time to complete it. From what I understand we need to add support for reading the NEXTAUTH_URL in order to properly deploy to Netlify right?

If that is the case you could add a extra section to do this in the following file:
https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/server/services/utils.ts#L11

Feel free to take a swing at it and see if it resolves the issue!

**Comment by julienhohm** [comment]
Hello,

I had the same issue with Nuxt 3.5.2 and @sidebase/nuxt-auth 0.5.0, and I don't know what change but I tried today to upload in my production netlify site and all is working fine!

I just put my origin in nuxt.config.ts: 
```
  auth: {
    origin: process.env.AUTH_ORIGIN,
```

and the environment variable in the setting section of netlify:
![image](https://github.com/sidebase/nuxt-auth/assets/32843802/d778ceea-029c-4a46-b750-d02da5d255db)

Maybe a Netlify patch?

**Comment by agracia-foticos** [comment]
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/025cc07b-4cb2-4ff1-abf7-acaf7ed4650f)
 Same issue

**Comment by zoey-kaiser** [comment]
Nitro patched a bug this summer, where Netlify was having issues setting cookies with Nuxt projects. Have you tried deploying since then, as I can imagine, this caused many more issues!

https://github.com/unjs/nitro/pull/1452

After their patch, I managed to deploy the NuxtAuthExample to Netlify. If the issues, persists, you are welcome to reopen this issue!
