### ISSUE TITLE
[0.6] Return status as Boolean instead of String

### ISSUE THREAD

**Issue by mrleblanc101** [sidebase/nuxt-auth#461]
Currently I can do `const { status } = useAuth()` but status is a String of value `authenticated | unauthenticated | loading` which is annoying for non-typescript user. Would it be possible to have a Boolean getter the `isLoggedIn` from `@nuxtjs/auth-next` ?

**Comment by zoey-kaiser** [comment]
@mrleblanc101, I had a quick talk with the rest of the team about implementation this and we decided against it. 
Our main concern is that adding this, may lead to confusion on what the actual status of the authentication is. Status has three different states and reducing these three to one boolean value, does not properly translate. 

Example:
- User logs in: `isLoggedIn: true`
- Session gets automatically updated (happens every 30 seconds): `isLoggedIn: false` (due to the status being `loading`

In this edge case the user would be logged in, but `isLoggedIn` would return false, as the status is loading. Being able to determine if the user was previously logged in and then the session is refetching, or the page is initially loading and we don't know yet if the user is logged in, would look the same.

However, I understand your use case, which is why I wrote a quick Nuxt Composable you can use in your project!

```js
// File: /composables/useIsLoggedIn.js
export default () => {
	const { status } = useAuth()
	const isLoggedIn = computed(() => {
		if (status === 'loading') {
			return false
		} else if (status === 'authenticated') {
			return true
		} else {
			return false
		}
	})
	return isLoggedIn
}
```

You can then use this composable without importing it in your other Vue files:

```vue
// File page.vue
<script setup>
const isLoggedIn = useIsLoggedIn()
</script>

<template>
	<div v-if='isLoggedIn'>
		Your Logged In!
	</div>
</template>
```
