### ISSUE TITLE
getting unauthenticated status even after getting access token form local provider backend api

### ISSUE THREAD

**Issue by AnilkrishnaD** [sidebase/nuxt-auth#482]
### Environment

This is my configuration file
// https://nuxt.com/docs/api/configuration/nuxt-config
```
export default defineNuxtConfig({
  app: {
    head: {
      title: "Turiya chat-app",
    },
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/styles/_include.scss" as *;',
        },
      },
    },
  },

  css: [
    "primevue/resources/themes/lara-light-blue/theme.css",
    "primevue/resources/primevue.css",
    "primeicons/primeicons.css",
  ],
  build: {
    transpile: ["primevue"],
  },
  modules: [
    "@vueuse/nuxt",
    "@nuxt/content",
    "@pinia/nuxt",
    "nuxt-simple-sitemap",
    "@nuxtjs/tailwindcss",
    "@sidebase/nuxt-auth",
  ],
  auth: {
    baseURL: "https://api.escuelajs.co/api/v1/auth/",
    // baseURL: process.env.API_BASE_URL,
    provider: {
      type: "local",
      endpoints: {
        signIn: { path: "/login", method: "post" },
        signOut: { path: "/logout", method: "post" },
        signUp: { path: "/register", method: "post" },
        getSession: { path: "/session", method: "get" },
      },
      token: {
        signInResponseTokenPointer: "/access_token",
        type: "Bearer",
        headerName: "Authorization",
      },
      // sessionDataType: {
      //   id: "string",
      //   name: "string",
      //   email: "string",
      // },
    },
    session: {
      // Whether to refresh the session every time the browser window is refocused.
      enableRefreshOnWindowFocus: true,

      // Whether to refresh the session every `X` milliseconds. Set this to `false` to turn it off. The session will only be refreshed if a session already exists.
      enableRefreshPeriodically: false,
    },
    globalAppMiddleware: {
      isEnabled: false,
    },
  },
  pinia: {
    autoImports: [
      // automatically imports `defineStore`
      "defineStore", // import { defineStore } from 'pinia'
      ["defineStore", "definePiniaStore"], // import { defineStore as definePiniaStore } from 'pinia'
    ],
  },
  devtools: { enabled: true },
  runtimeConfig: {
    // The private keys which are only
    // available within server-side

    // Keys within public, will be also be
    // exposed to the client-side
    public: {
      baseURL: process.env.API_BASE_URL,
      siteUrl: process.env.SITE_URL,
      // siteUrl: "http://localhost:3000/",
      // API_KEY: "https://convai.turiyatree.in:8000",
    },
  },
  ssr: true,
});
```

### Describe the bug

i am getting the acces token from the backend, while showing stauts initially it shows loading and token but whith in seconds again it is showing unauthenticated

**Comment by luisfrocha** [comment]
I have this issue at the moment. I see the token in the cookies, it authenticates, and about 15-20 seconds after login, it fails. The token says it expires way after, though.

**Comment by pjk1413** [comment]
I have noticed that on a refresh the cookie disappears and state is not longer persisted.

**Comment by codaxiom** [comment]
> I have noticed that on a refresh the cookie disappears and state is not longer persisted.

Same problem here

**Comment by adesousa** [comment]
Hi, same problem here. Working great in HTTP but when I'm testing in https self signed by Nuxt, nothing is working then. Have you find a workaround ?

**Comment by zoey-kaiser** [comment]
Hi @AnilkrishnaD everything in your nuxt config looks good, could you (or someone else experiencing this issue) please provide a reproduction for this issue?

**Comment by adesousa** [comment]
Hi @zoey-kaiser ! 
I'm still in dev mode. 
But it all started with a bug related to the "navigateTo" which throws error on local provider when in HTTPS. Otherwise, when I was not exposing in https mode my app, all was working fine.
As I was developing with 0.6.0-beta.5 I saw your fix and tried to update both nuxt and nuxt-auth.

Then, the problem evolved to no more having this navigateTo error, but staying in unauthenticated mode regardless I've been well authenticated. 

It seems that the cookie is not set in https mode (I tested in http mode and cookie is set and I'm authenticated) so, when I call login endpoint with the good credentials I'm redirected to my admin page but instantly got redirected to login page as I'm unauthenticated.
Here my login code who works: 
try {
    await signIn('local', {
      callbackUrl: '/admin',
      redirect: true,
      username: email.value,
      password: password.value
    })

Again everything is fine in npm run dev but when I'm going with npx nuxi dev --host --https everything gets down.

Here an extract of my package.json versions: 

    "@sidebase/nuxt-auth": "0.6.0-rc.0",
    "@types/jsonwebtoken": "^9.0.4",
    "nuxt": "^3.8.0"

Any ideas ?

**Comment by zoey-kaiser** [comment]
> It seems that the cookie is not set in https mode (I tested in http mode and cookie is set and I'm authenticated) so, when I call login endpoint with the good credentials I'm redirected to my admin page but instantly got redirected to login page as I'm unauthenticated.

Hmm, there issues are pretty tricky to debug correctly. May I ask a few more questions about your deployment?

- How are you deploying your Nuxt App?
- Is there any kind of layer on top of your application (cloud flare, reverse proxy etc.)
- Does this also happen when you build the application and run it locally (not in dev mode)?

I am trying to narrow down the places where this issue originates from at the moment. If building and starting the application works locally, we will have to dive a bit deeper into your deployment and see if there is anything blocking the cookies, or if it really is due to the https.

>  But it all started with a bug related to the "navigateTo" which throws error on local provider when in HTTPS. Otherwise, when I was not exposing in https mode my app, all was working fine.

Yes, this was an issue with the local provider when redirecting to pages outside of the application. In `0.6.0-rc.1` you can override this behavior by passing `{.external: true }` in the additional props of the `signIn`, `signOut`, `session` functions. 

```ts
await signIn(credentials, { callbackUrl: 'https://sidebase.io', external: true })
```

**Comment by adesousa** [comment]
Hi @zoey-kaiser !
Thanks for your time and quick reply.
Yes it does work locally as in dev mode, once I'm getting in https mode it's no longer working.
I have no layer on top, just developing from my own Macbook.
I still have not tried by building the app, I'm gonna try it today and give you feedback on this.

**Comment by adesousa** [comment]
Ok this is very weird, but I've just tested a build in production mode with a real certificate and it's working fine ... I don't know what to say. Locally it's not working with npx nuxi dev -https but in production it's working !
Thanks for the help !

**Comment by zoey-kaiser** [comment]
> Ok this is very weird, but I've just tested a build in production mode with a real certificate and it's working fine ... I don't know what to say. Locally it's not working with npx nuxi dev -https but in production it's working !

Hmm, Its great to hear that it does work in production! But of course it is annoying that the Nuxt self assigned certificate does not properly work. 

I will bring this up with the team and we can look into it. For now I would say that we don't support it. For anyone else in this issue, lets try and split up the issues properly. 

If you are using the `npx nuxi dev -https` and it is not working, please test it in production. If it still does not work properly in production please open a new issue with more context to your setup!

As for the issue with nuxt dev -https, ill open a new issue about this and see when we can look into supporting this!
