### ISSUE TITLE
Playgrounds not working correctly

### ISSUE THREAD

**Issue by codetheorist** [sidebase/nuxt-auth#489]
### Environment

**Root**
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.1
- Nuxt Version:     3.6.4
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------ 
**Local Playground**
------------------------------
- User Config:      modules, build, auth
- Runtime Modules:  ../src/module.ts
------------------------------
**AuthJS Playground**
------------------------------
- User Config:      modules, auth
- Runtime Modules:  ../src/module.ts
------------------------------

### Describe the bug

Cloned the repo with a view to fixing some bugs and closing some issues however, I was unable to get the module running in the playgrounds provided, with a variety of errors.

**Comment by zoey-kaiser** [comment]
Hi @codetheorist,

could you please give a bit more information on what was happening? Which errors did you run into?

**Comment by zoey-kaiser** [comment]
Hi @polymorph233, does this happen with both playgrounds are only one? Ill try and look into reproducing it this afternoon if I can some time!

Otherwise, I assume you changed nothing about the playgrounds, aka this was happening on main. Ill use your node version etc. and see if I have the same issues 🎉

**Comment by polymorph233** [comment]
Hi, this is only related to the authjs playground. But maybe I have found the cause.

In fact this is because I used `npm` instead of `pnpm` for installing dependencies. The playground works perfectly under `pnpm install`.

In case for reproduce the problem, the steps are following:

- Clone the `nuxt-auth` repo
- Down to `playground-authjs` and execute a `npm install`, wait until this command fails
- Go back to the parent directory and execute `npm install`, which will succeed
- Go down again to the folder `playground-authjs` and execute a `npm install`, which will succeed
- Run the `dev` command of nuxt, and it will fail with the mentioning error

Normally this procedure will succeed if use `pnpm` as the project indicates.

Here are my package manager versions:

$ npm --version
9.8.0
$ node --version
v20.5.0
$ pnpm --version
8.6.0

**Comment by zoey-kaiser** [comment]
Hi @polymorph233,

I had already expected something like this. If the project works with `pnpm` then I don't think I would change anything here. These multiproject setups are always a bit complex and finiky, which is why we went with pnpm over npm (as it generally does dependency linking a bit better). 

Are you okay with using pnpm over npm?

**Comment by polymorph233** [comment]
I am ok with working with `pnpm`. I am currently not using this module in fact (due to some issues unresolved with Keycloak) but I think previous discussions may allow someone running into similar case to refer to.

By the way, this may remind me of my post on the forum several days ago about some strange behavior when integrating with Keycloak provider. 

Not sure if switching to `pnpm` may solve this issue (the project I am working on was using yarn). Maybe worth a try. I will come back later if this problem is solved.
