### ISSUE TITLE
How to get session in [...].ts | NuxtAuthHandler get session from event

### ISSUE THREAD

**Issue by MuhammadKhizar7** [sidebase/nuxt-auth#52]
### Describe the feature

How can we get a session from NuxtAuthHandler as I am able to understand how to get event as I see example 
```
export default eventHandler(async (event) => {
  const session = await getServerSession(event)
})

```

it use event to get session data

**Comment by BracketJohn** [comment]
Hey @MuhammadKhizar7!

I transferred this issue here, as https://github.com/sidebase/nuxt-session is another module than the auth-module that you're asking questions for here (: 

Regarding your question: You cannot get the server-session inside the `authorize` call as no session exists at that point -> it's the place where it's checked whether the user provided the correct credentials. You can only access the session after the user successfully logged in. The `authorize` function is effectively the place the session is created at / after.

What's your use-case here / Why do you need a session at that point?

**Comment by MuhammadKhizar7** [comment]
Thanks, I also have issue getting session inside server route.

```
import { createPost } from '../../data/posts'
import { getServerSession } from '#auth'
export default defineEventHandler(async (event) => {
  const session = await getServerSession(event)
  const body = await readBody(event)
  console.log(body)
  console.log(session)
  return createPost(body)
})
```
Its shows blew error: **This action with HTTP POST is not supported by NextAuth.js** 

I also check nextAuth as it coming from there and found this link https://github.com/nextauthjs/next-auth/discussions/3107
but in my case I am using api/auth correct URL as this above link says
So I think its look like nuxt-auth issue

**Comment by BracketJohn** [comment]
Yes, this indeed is a bug - I already know where it comes from: `getServerSession` is a special wrapper around the nuxtAuthHandler endpoint. It basically bassed in the `event` unaltered and only sets a flag to true.

This means that the method is also passed along, although it should be `GET` in every case!

See
https://github.com/sidebase/nuxt-auth/blob/44a159c5d936869c3c9d5e41d337a1578174bec1/src/runtime/server/services/nuxtAuthHandler.ts#L100

Thanks, will fix this ASAP and do a new release (:

**Comment by MuhammadKhizar7** [comment]
Thanks a lot

**Comment by BracketJohn** [comment]
Let's keep the issue opened until we resolved it via a PR!

**Comment by BracketJohn** [comment]
@MuhammadKhizar7 the issue was fixed and the release for it is out: https://github.com/sidebase/nuxt-auth/releases/tag/0.2.0

Use it as `npm i -D @sidebase/nuxt-auth` (:

**Comment by MuhammadKhizar7** [comment]
@BracketJohn Thanks
