### ISSUE TITLE
`Self-signed certificate in certificate chain` error in production environment

### ISSUE THREAD

**Issue by ymansurozer** [sidebase/nuxt-auth#545]
### Environment

![image](https://github.com/sidebase/nuxt-auth/assets/40335724/b15d9daa-b461-44c7-a3db-f20b7941120e)

Edit:
Versions from `package.json`:
```
"dependencies": {
    "next-auth": "4.21.1",
}
"devDependencies": {
    "@sidebase/nuxt-auth": "^0.6.0-beta.6",
}
```

I am deploying on Digital Ocean's app platform.

### Describe the bug

All my requests to the `/api/auth` endpoints return `self-signed certificate in certificate chain` error. This only happens in my production environment, everything is fine in dev.

I am not using any self-signed certificates myself in the app.

**Tried**
I saw some issues in the repo saying the `baseUrl` is not being set correctly when only specified in `nuxt.config.ts`. So I tried adding these to my `.env` but I still get the same error:
```
NEXTAUTH_URL=mydomain.com/api/auth
AUTH_ORIGIN=mydomain.com
```

**Workaround**
If I set `process.env.NODE_TLS_REJECT_UNAUTHORIZED` to `0`, all works well.

### Additional context

Relevant parts of my `nuxt.config.ts`:
```
auth: {
    baseURL: `${process.env.APP_URL}/api/auth`,
    globalAppMiddleware: {
      isEnabled: false,
      allow404WithoutAuth: true,
    },
    provider: {
      type: "authjs",
    },
  },

runtimeConfig: {
    authSecret: process.env.AUTH_SECRET,
},
```

Relevant parts of my `api/auth/[...].ts`:
```
import CredentialsProvider from "next-auth/providers/credentials";
import { NuxtAuthHandler } from "#auth";

const config = useRuntimeConfig();

export default NuxtAuthHandler({
  secret: useRuntimeConfig().authSecret,

  session: {
    strategy: "jwt",
  },

  pages: {
    signIn: "/signin",
    signOut: "/",
    error: "/error",
  },

  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: "Credentials",
      credentials: {
        username: { label: "Username", type: "text" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials: any) {
        // My password authorization logic
      },
    }),
  ],
});
```

### Logs

```shell
The response from the `api/auth/callback/credentials` endpoint is this:

{
    "url": "https://mydomain/api/auth/error?error=self-signed%20certificate%20in%20certificate%20chain"
}
```

**Comment by zoey-kaiser** [comment]
Hi @ymansurozer, 

Generally this issue results from NextAuth, not being able to verify your SSL certificate. You already used the workaround of setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED` to 0, however it is recommended that you instead reference your SSL certificate to your node environment. 

You can do this by running:

```
set NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem
```

Or defining the location in your node environment. You can read more about this in this medium article:
https://medium.com/@jonatascastro12/understanding-self-signed-certificate-in-chain-issues-on-node-js-npm-git-and-other-applications-ad88547e7028

What confuses me a little bit is that you say you don't use a self signed SSL certificate, however as this issue is a result of NextAuth and not NuxtAuth, we won't be able to resolve this issue, as it most likely has to due with another code base. I will keep this issue open, in case members of our community have any idea, however I would recommend opening another issue on https://github.com/nextauthjs/next-auth, as they will properly understand the logic behind this error more and can patch any issue in their code.

**Comment by ymansurozer** [comment]
Thank you very much @zoey-kaiser! I've finally solved this. It seems to be originated from `pg` package I used to connect to my database from `[...].ts`. I used Prisma instead and all works great now!

**Comment by zoey-kaiser** [comment]
> Thank you very much @zoey-kaiser! I've finally solved this. It seems to be originated from pg package I used to connect to my database from [...].ts. I used Prisma instead and all works great now!

I am very happy to hear this! I hope everything from here on out is smooth sailing ⛵
