### ISSUE TITLE
Refresh provider collection issue

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth#634]
## Goal

Ensure the `refresh` provider works as expected.

## Context

In https://github.com/sidebase/nuxt-auth/pull/581 we merged the refresh provider. Since then new issues have been opened, that point out issues not found during initial review. This issue aims to collect all of them to provide a better overview.

## Issues

- [x] https://github.com/sidebase/nuxt-auth/issues/609
- [x] https://github.com/sidebase/nuxt-auth/issues/626
- [x] https://github.com/sidebase/nuxt-auth/issues/480
- [x] https://github.com/sidebase/nuxt-auth/issues/620
- [x] https://github.com/sidebase/nuxt-auth/issues/635

**Comment by AlejandroAkbal** [comment]
Hey, I love this library, and I'm so saddened by the fact that 90% of what I need works, but this final and important piece is missing (keeping auth after browser close/refresh)

Is there some way I can contribute to expedite this issue?

**Comment by zoey-kaiser** [comment]
> Is there some way I can contribute to expedite this issue?

Hi @AlejandroAkbal of course! I think you could help in 2 important ways:

1. indicating which issues are blocking you most, so we can prioritize the fixes
2. directly begin investigations or implement fixes yourself

To be completely transparent: I have recently picked up a new project, where I need to dedicate a lot of my time to. Therefore I am really having issues finding enough time to dedicate to maintaining sidebase properly, which does sadden me a lot. I have enough time to still review, merge and release external pull requests, but am really struggling to find the time to properly investigate and push fixes and new features myself. 
Therefore if you manage to find a bit of time to either research for fix the issues yourself, I can get around to a review within the week. As they are also bug fixes and not completely new features, there also is not much discussion to be had about how the feature works etc. 

Thank you so much for your interest in sidebase ❤️

**Comment by AlejandroAkbal** [comment]
Thank you for your honesty, no problem!

1. My most important issue was refresh provider, which is now out, awesome!

1.1 Other issue is keeping auth state, which is (hopefully) fixed with the cookie workaround, see https://github.com/sidebase/nuxt-auth/issues/626#issuecomment-1877418545

1.2 Another issue was that the refresh request, is send with a HTTP POST Body that cannot be changed, and my API was expecting a different structure for the Body request
It was  `{"refresh_token":"blabla"}` instead of `{"refreshToken":"blabla"}`

Hoping I can look around and make a PR for this in the future
