### ISSUE TITLE
`getServerSession` is broken using local provider

### ISSUE THREAD

**Issue by FrankoFM** [sidebase/nuxt-auth#811]
### Environment

0.8.0

### Reproduction

More or less following the [`playground-local`](https://github.com/sidebase/nuxt-auth/tree/main/playground-local)

### Describe the bug

When using `getServerSession` it always results in a 500 Error with the message:

> Tried to get server session without setting up an endpoint to handle authentication (see https://github.com/sidebase/nuxt-auth#quick-start)

### Additional context

I currenly dont have the time to dive deeper into this, but thats what I found:
`getServerSession` is defined [here](https://github.com/sidebase/nuxt-auth/blob/ba6d811b83230a82789c3d56fe643b4737898612/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L187)
It will check for [`preparedAuthHandler`](https://github.com/sidebase/nuxt-auth/blob/ba6d811b83230a82789c3d56fe643b4737898612/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L194C8-L194C27), followed by a fetch, then [checking again](https://github.com/sidebase/nuxt-auth/blob/ba6d811b83230a82789c3d56fe643b4737898612/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L199), without ever setting the value, so it has to result in said error.

**Comment by FrankoFM** [comment]
I also noticed that the `/session` endpoint is hardcoded [here](https://github.com/sidebase/nuxt-auth/blob/ba6d811b83230a82789c3d56fe643b4737898612/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L198), but it should use the value defined in the nuxt config.

**Comment by zoey-kaiser** [comment]
`getServerSession` is not supported by the `local` or `refresh` providers at the moment, as the `local` and `refresh` providers were built to also support static deployments, which is why they placed a focus on client-side interactions. 

There is currently an open issue (https://github.com/sidebase/nuxt-auth/issues/854) and PR (https://github.com/sidebase/nuxt-auth/pull/855) that aims to add `getServerSession` and `getToken` to the `local` and `refresh` providers. You can follow along with the process in these two places!
