### ISSUE TITLE
Look into pages not being correctly protected

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth#84]
### Describe the bug

A user on our discord reported the following bug in the newest version of `nuxt-auth` v0.3.0 Alpha 3. We should look into resolving this before our release:

https://a.cl.ly/7KujyX7e?method=GET

**Comment by JoaoPedroAS51** [comment]
This issue was happening before the alpha release as well

**Comment by zoey-kaiser** [comment]
> This issue was happening before the alpha release as well

Good to know. That is definitely a big problem! We will prioritize looking into it ASAP!

**Comment by JoaoPedroAS51** [comment]
It doesn't happen on dev. To tested it we need to build the app `npm run build && npm run preview`

**Comment by JoaoPedroAS51** [comment]
@zoey-kaiser @BracketJohn I found what causes the issue. Is calling `navigateTo` with `external: true` option.

**Comment by BracketJohn** [comment]
Will do, thanks for looking into this! ❤️

**Comment by JoaoPedroAS51** [comment]
I found a way to fix it. In the [navigateTo util](https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/utils/url.ts#L14), we change the `window.location.href = href` to `window.location.replace(href)`. This will navigate to the URL without adding a new record to the history. But we should add an `if` to change this behaviour, since we only want to use `window.location.replace` when calling from middleware.
