### ISSUE TITLE
Ideas to more explicit with the next-auth providers dependencies

### ISSUE THREAD

**Issue by profblackjack** [sidebase/nuxt-auth#99]
### Describe the feature

I noticed that the current recommended pattern for providers is to import from the `next-auth` package. 

As this package is a dependency of `@sidebase/nuxt-auth`, and not necessarily a dependency of the `nuxt` application using `@sidebase/nuxt-auth`, it means either relying on the implicit hoisting of dependencies by a subset of package managers, or explicitly adding `next-auth` as a dependency in the `nuxt` application.

I chose to do the latter for better explicit dependency tracking and to avoid potential conflicts with pnpm.

Today, I encountered an issue due to a minor version bump of  `next-auth` during a routine package upgrade, and noticed that in `@sidebase/nuxt-auth` a specific version of `next-auth` is pinned.

I pinned to the specific version in my project's package.json, but it got me wondering if there was a better way.

A couple options I see:
- explicitly re-export the providers from `next-auth` in `@sidebase/nuxt-auth`, so the exact versions from `next-auth` that work with `@sidebase/nuxt-auth` can be used
- add `next-auth`  to peerDependencies  in addition to dependencies in `@sidebase/nuxt-auth`, so package managers will present a warning if there's no explicit `next-auth` dependency in the `nuxt` project, or if the explicit dependency falls outside  `@sidebase/nuxt-auth`'s pinned version of `next-auth`

**Comment by BracketJohn** [comment]
Hey there @profblackjack! 👋 

Thanks for the well though-out, long form proposal ❤️ 

You are right that drift of the underlying `next-auth` dependency can pose a risk. Most recently we encountered this in #89 (which is probably the same issue that you encountered).

Only _today_ when we fixed #89 + released `0.3.0` we fixed the `next-auth` dependency (instead of allowing small fluctuation via the `^`). Bascially, this should already fix the problem you describe above: When you install `nuxt-auth@>=0.3.0` it should now automatically install `next-auth@4.18.0` no matter what.

Of course you could still manually override this with a "bad" version or accidentally have a second `next-auth` version installed due to some dependency. This seems very unlikely to me however, because as you're saying yourself: We're in a `nuxt` world!

So, do you think that the fix of #89 is enough to address this proposal? Btw, see https://github.com/sidebase/nuxt-auth/pull/94 for the fix itself where we pinned the `next-auth` version.

**Comment by profblackjack** [comment]
Hi @BracketJohn,

I think it's specifically because of the pinning inside nuxt auth that I made this issue.

For hoisting package managers (npm, yarn), I can ignore explicitly adding next-auth as a dependency, but can still access providers via `import x from 'next-auth/providers/x`, because the next-auth dependency is hoisted to the top level of node_modules and can be referenced by the nuxt project even though it's not a dependency of the project.

However, package managers like pnpm do not perform hoisting, and you don't get this side effect where you can access modules outside of your explicit dependencies.

In this case, I currently need to add next-auth as a (dev)dependency so I can grab providers from it, and there's no indication that I might be adding a version incompatible with next-auth.

**Comment by BracketJohn** [comment]
Hey @profblackjack 👋 

you are right - we'll switch the internal core to the `auth.js` soon (the framework independent successor of NextAuth). As part of this, we'll address this issue (:

**Comment by BracketJohn** [comment]
Moved this into #117 and will close this issue to keep the repo clean. Thanks again @profblackjack and do know that this will be resolved - just as part of #117.

**Comment by BracketJohn** [comment]
Just as a quick fyi for everyone following this issue: This has already happened, in `0.4.0` `next-auth` is a peer dependency (: 

At the moment we're still on alpha-releases, but it's looking quite stable already, so if this is a pressing issue to you, you can upgrade to get the benefits.
